controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_controller:
      type: "joint_state_controller/JointStateController"

    diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"
      joints:
        - wheel_left_joint
        - wheel_right_joint